services:
  bank-account-discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  bank-account-config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - "9999:9999"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      bank-account-discovery-service:
        condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    restart: always

  bank-account-account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - "8383:8383"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8383/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      bank-account-customer-service:
        condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    restart: always

  bank-account-customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - "8282:8282"
    expose:
      - "8282"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8282/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      bank-account-config-service:
        condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    restart: always

  bank-account-gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8888:8888"
    expose:
      - "8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      bank-account-config-service:
        condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    restart: always

networks:
  default:
    driver: bridge
