version: '3.8'
services:
  postgres:
    image: postgres:16.2
    container_name: account-service_db
    environment:
      POSTGRES_USER: kamdoum
      POSTGRES_PASSWORD: danielle1234
      POSTGRES_DB: account-service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

