version: '3.8'
services:
  postgres:
    image: postgres:16.2
    container_name: customer_db_container
    environment:
      POSTGRES_USER: kamdoum
      POSTGRES_PASSWORD: danielle1234
      POSTGRES_DB: customer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

